### ISSUE TITLE
create_package should use own templates

### ISSUE THREAD

**Issue by jhollway** [globalgov/qDatr#44]

**Comment by henriquesposito** [comment]
Since we are adding our own templates and path to the qDatr package, several helper functions were added to the package script on qDatr that were taken directly from usethis. This is because these are functions not exported in usethis, thus, usethis::functionname does not work for them. Also because of this, several dependencies were listed as under suggests in the description so that the qDatr package work, for the time being.

**Comment by henriquesposito** [comment]
The path to our own templates and folder to store templates in qDatr are done. The work now is on setting up the templates themselves.
